# Generated by Django 4.2.4 on 2023-09-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='Seller',
        ),
    ]
