# Generated by Django 4.2.4 on 2023-09-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0002_alter_seller_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerApp.seller')),
            ],
        ),
    ]
