# Generated by Django 4.2.4 on 2023-09-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0003_theater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theater',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.AlterModelTable(
            name='theater',
            table='Theater',
        ),
    ]
