# Generated by Django 4.2.4 on 2023-09-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=50)),
                ('time_duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.admin')),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
