# Generated by Django 4.2.4 on 2023-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(unique=True, verbose_name=50),
        ),
    ]
